export const copy = {
  en: {
    siteTitle: 'CrewBee | Agent Teams for OpenCode',
    siteDescription: 'CrewBee is an Agent Team framework for OpenCode that lets you design different Agent Teams for different tasks or projects, and switch flexibly between single-agent execution and multi-agent collaboration based on task complexity.',
    nav: {
      features: 'Highlights', coding: 'Coding Team', context: 'Project Context', how: 'How It Works', docs: 'Docs', github: 'GitHub ↗', installCli: 'Install CLI', toggleTheme: 'Toggle dark mode', toggleMenu: 'Toggle navigation menu', switchLanguage: '中文', switchLanguageLabel: 'Switch language'
    },
    hero: {
      titlePrefix: 'Design different Agent Teams', titleHighlight: 'for different tasks.', description: 'CrewBee is an Agent Team framework for OpenCode that lets you design different Agent Teams for different tasks or projects, and switch flexibly between single-agent execution and multi-agent collaboration based on task complexity.', bullets: ['Design different Teams for code, research, writing, launch work, and long-running projects.', 'Keep simple tasks lightweight, and use team collaboration when work needs support, review, and verification.', 'Reduce the main agent’s context and attention load through context-isolated delegation.'], getStarted: 'Get Started', viewGithub: 'View on GitHub', floating: ['Design Team', 'Choose Mode', 'Delegate in Context']
    },
    status: ['Task-specific Teams', 'Single-agent or Multi-agent', 'Context-isolated Delegation', 'Built-in Coding Team', 'Project Context Next', 'OpenCode MVP'],
    features: {
      title: 'CrewBee Highlights', subtitle: 'From task-specific Agent Teams and flexible single-agent / multi-agent execution to context ownership, isolated delegation, Coding Team review, Project Context, and reusable Team templates.', cards: [
        { title: 'Design Different Agent Teams for Different Tasks and Projects', desc: 'Model different work as separate Teams, each with its own roles, rules, workflow, and completion criteria.' },
        { title: 'Switch Between Single-agent and Multi-agent Collaboration Based on Task Complexity', desc: 'Keep simple tasks fast with a single agent, and use support agents, review, verification, and completion gates for complex work.' },
        { title: 'Main Agent Owns the Most Complete Context', desc: 'The main agent keeps the user goal, project constraints, support findings, review feedback, and verification results together for better decisions.' },
        { title: 'Context-isolated Delegation Reduces Context and Attention Load', desc: 'Support agents work in dedicated contexts for exploration, research, and review, then return high-signal findings to the main agent.' },
        { title: 'Built-in Mature Coding Team with Review and Completion Criteria', desc: 'CrewBee includes a Coding Team for code development, fixing, debugging, refactoring, verification, and final closure.' },
        { title: 'Automatically Maintained Project Context Across Sessions', desc: 'Next: maintain project positioning, framework design, history, current state, and plans for long-running work.', tag: 'Next' },
        { title: 'Copyable, Modifiable, and Contributable Team Templates', desc: 'Teams are engineering assets that can be copied, modified, versioned, and contributed by the community.' }
      ]
    },
    why: {
      titleBeforeBreak: 'Agent workflows already have team structure.', titleAfterBreak: 'They need clearer task, context, and completion boundaries.', paragraphs: ['In real development, implementation, code exploration, external research, review, verification, and project-context maintenance are not the same kind of work.', 'CrewBee turns these implicit structures into explicit Agent Teams: different tasks can use different Teams, simple tasks can stay lightweight, and complex tasks can use support, review, and verification.'], emphasis: 'CrewBee turns Agent Teams from hidden convention into runnable, maintainable, and reusable engineering assets.'
    },
    how: { title: 'How It Works', subtitle: 'From Team definition to OpenCode runtime, then choose the right execution mode for the task.', steps: [{ step: 'Define Team', desc: 'Define Teams, Leaders, members, rules, review flow, and completion criteria for different tasks or projects.' }, { step: 'Project to OpenCode', desc: 'CrewBee projects Team definitions into OpenCode agents that can be selected, run, and delegated to.' }, { step: 'Choose Execution Mode', desc: 'Use a single agent for simple tasks, or multi-agent collaboration with support context and review for complex work.' }, { step: 'Delegate, Return, Close', desc: 'Support agents work in isolated contexts; the main agent collects high-signal findings and owns final closure.' }] },
    team: { badge: 'Templates', title: 'Teams are copyable, modifiable, and contributable engineering assets.', paragraphs: ['CrewBee organizes Agent Teams as clear file-based assets.', 'Use the built-in Coding Team, copy a template, adjust roles, shared rules, review flow, and completion criteria, then evolve it into your own Team.'], files: ['team.manifest.yaml      # Team positioning, leader, members, workflow', 'team.policy.yaml        # Shared rules, safety boundaries, quality floor', 'coding-leader.agent.md  # Main agent, context owner, final closure', 'codebase-explorer.agent.md', 'web-researcher.agent.md', 'reviewer.agent.md       # Independent review and completion criteria', 'TEAM.md                 # Human-facing Team guide'] },
    codingTeam: { badge: 'Coding Team', title: 'Built-in mature Coding Team. Not just one Coder.', subtitle: 'For code development, fixing, debugging, refactoring, and verification, CrewBee provides clear roles, review flow, and completion criteria.', roles: [{ name: 'coding-leader', desc: 'Default entry point, main context owner, and final closure owner.' }, { name: 'coding-executor', desc: 'Executes clear implementation, fixes, debugging, and local refactoring.' }, { name: 'codebase-explorer', desc: 'Finds code entry points, call chains, similar implementations, and historical clues.' }, { name: 'web-researcher', desc: 'Researches official docs, external references, open-source implementations, and version differences.' }, { name: 'reviewer', desc: 'Independently reviews risk, omissions, verification evidence, and completion criteria.' }], gateTitle: 'Completion Gate', gates: ['Target issue is located', 'Change has clear evidence', 'Necessary implementation or fix is complete', 'Available diagnostics / build / tests have run', 'Reviewer found no real blocker', 'Residual risk and unverified items are stated'] },
    projectContext: { badge: 'Next', title: 'Automatically maintained Project Context across sessions.', subtitle: 'Let long-running projects keep high-signal summaries of positioning, framework design, history, current state, and plans, reducing repeated explanation and repeated code reading.', cards: [{ title: 'Maintain Project Summaries', desc: 'Track project positioning, framework design, historical decisions, current state, known risks, and next actions.' }, { title: 'Reduce Manual Re-briefing', desc: 'New sessions do not have to restart from project background, prior decisions, and current plans.' }, { title: 'Guide Code Reading', desc: 'Agents can use Project Context to locate relevant modules before targeted code reading, avoiding wasteful full-repo scans.' }], flow: ['Session Start: restore project positioning and current plan', 'During Work: use summaries to guide focused code and document reading', 'Session End: update implementation state, decisions, risks, and next actions', 'Next Session: continue from the latest project context'] },
    builders: { title: 'For the Builders', subtitle: 'Built for people who already maintain agent workflows by hand.', cards: [{ role: 'OpenCode power users', desc: 'Want clearer Teams, execution-mode choices, and delegation workflows instead of scattered agent configs.' }, { role: 'Agent workflow builders', desc: 'Want to turn working styles into runnable, copyable, and contributable Agent Teams.' }, { role: 'AI Coding users', desc: 'Want simple coding tasks to stay lightweight and complex tasks to include exploration, review, and completion criteria.' }, { role: 'Long-running project maintainers', desc: 'Want project positioning, framework design, history, current state, and plans to survive across sessions.' }] },
    opencode: { title: 'OpenCode MVP path is already connected.', description: 'CrewBee can project Team definitions into OpenCode agents that are selectable, runnable, and delegation-ready.', links: ['Read installation guide', 'View OpenCode runtime docs'], proofs: ['Team / Agent definitions', 'Team Library assembly and validation', 'Runtime Projection', 'Formal leader as default entry', 'OpenCode agent config projection', 'Session binding', 'Delegation tooling', 'User-level install and doctor checks'] },
    faq: { badge: 'FAQ', heading: ['Clarity', 'Through', 'Structure.'], items: [{ q: 'Is CrewBee a prompt pack?', a: 'No. CrewBee uses prompts, but its core is Team definitions, Agent profiles, Runtime Projection, session binding, and delegation tooling. It turns agent workflows into maintainable, runnable Team assets.' }, { q: 'Does CrewBee make every task multi-agent?', a: 'No. CrewBee is about choosing the right execution strength. Simple tasks can stay fast with a single agent; complex tasks can use support agents, review, verification, and completion gates.' }, { q: 'Why should the main agent own the most complete context?', a: 'In complex work, support agents only see part of the picture. CrewBee lets the main agent collect user goals, project constraints, support findings, review feedback, and verification results before final decisions.' }, { q: 'What is context-isolated delegation?', a: 'Support agents do code exploration, research, review, or multimodal reading in dedicated contexts, then return high-signal findings to the main agent. This reduces main-agent context and attention load.' }, { q: 'Which hosts are supported?', a: 'CrewBee currently prioritizes OpenCode. Its definition layer is designed to stay host-adaptable for future runtimes.' }, { q: 'Is Project Context fully complete today?', a: 'Project Context is the next major CrewBee direction: automatically maintaining project positioning, framework design, history, current state, and plans across sessions.' }] },
    acknowledgements: { badge: 'Acknowledgements', title: 'Inspired by the open-source agent ecosystem.', paragraphs: ['CrewBee is inspired by OpenCode and community projects such as oh-my-openagent. These projects helped make agent-team workflows visible and practical in real development environments.', 'CrewBee continues this direction by turning Agent Teams into manageable, host-adaptable, and reusable engineering assets.'] },
    footer: { docs: 'Docs', license: 'License' }
  },
  zh: {
    siteTitle: 'CrewBee | 面向 OpenCode 的 Agent Team 框架',
    siteDescription: 'CrewBee 是一个面向 OpenCode 的 Agent Team 框架，支持为不同任务 / 项目设计不同的 Agent Team，并根据任务复杂度灵活切换单 Agent 执行与多 Agent 协作。',
    nav: { features: '亮点', coding: 'Coding Team', context: 'Project Context', how: '工作方式', docs: '文档', github: 'GitHub ↗', installCli: '安装 CLI', toggleTheme: '切换深色模式', toggleMenu: '切换导航菜单', switchLanguage: 'EN', switchLanguageLabel: '切换语言' },
    hero: { titlePrefix: '为不同任务设计不同的', titleHighlight: 'Agent Team。', description: 'CrewBee 是一个面向 OpenCode 的 Agent Team 框架，支持为不同任务 / 项目设计不同的团队，并根据任务复杂度灵活切换单 Agent 执行与多 Agent 协作。', bullets: ['为代码、调研、写作、推广和长期项目设计不同 Team。', '简单任务保持轻量，复杂任务启用团队协作、review 和验证。', '通过上下文隔离式委派，降低主 Agent 的上下文与注意力负担。'], getStarted: '开始使用', viewGithub: '在 GitHub 上查看', floating: ['设计 Team', '选择模式', '隔离式委派'] },
    status: ['任务专用 Team', '单 Agent 或多 Agent', '上下文隔离式委派', '内置 Coding Team', 'Project Context Next', 'OpenCode MVP'],
    features: { title: 'CrewBee 的核心亮点', subtitle: '从为不同任务 / 项目设计不同 Agent Team、根据任务复杂度灵活切换单 Agent 与多 Agent 协作模式、主 Agent 持有最完整上下文、上下文隔离式委派，到内置成熟 Coding Team 和跨会话 Project Context，把 Agent Team 变成可运行的工程资产。', cards: [
      { title: '为不同任务 / 项目设计不同 Agent Team', desc: '不同任务可以拥有不同角色分工、规则、流程和完成标准，而不是共用一套越来越长的通用 prompt。' },
      { title: '根据任务复杂度灵活切换单 Agent 与多 Agent 协作模式', desc: '简单任务保持快速响应，复杂任务启用支援 Agent、review、验证和完成闸门。' },
      { title: '主 Agent 持有最完整的上下文，保证决策依据的全面性', desc: '主 Agent 汇总用户目标、项目约束、支援结论、review 意见和验证结果，保证关键决策依据更全面。' },
      { title: '上下文隔离式委派，降低主 Agent 的上下文与注意力负担', desc: '支援 Agent 在独立上下文中完成探索、研究和审查，只把高信号结论回传给主 Agent。' },
      { title: '内置成熟 Coding Team，含 review 方式与验收标准', desc: '内置 Coding Team 提供清晰角色分工、review 方式与验收标准，适合代码开发、修复、调试和验证。' },
      { title: '跨会话自动维护 Project Context', desc: '下一阶段：持续维护项目定位、框架设计、历史记录、当前状态与计划，让长期项目不必每次从零解释。', tag: 'Next' },
      { title: '可复制、可修改、可贡献的 Team 模板体系', desc: 'Team 是可复制、可修改、可版本化、可贡献的工程资产，可以沉淀为团队自己的 Agent 工作方式。' }
    ] },
    why: { titleBeforeBreak: 'Agent 工作流本来就有团队结构。', titleAfterBreak: '只是缺少清晰的任务边界、上下文边界和完成标准。', paragraphs: ['在真实开发中，代码实现、代码探索、外部调研、review、验证和项目上下文维护，本来就不是同一种工作。', 'CrewBee 把这些隐含结构整理成显式的 Agent Team：不同任务可以用不同 Team，简单任务可以保持轻量，复杂任务可以启用支援、审查和验证。'], emphasis: 'CrewBee 让 Agent Team 从隐含约定，变成可运行、可维护、可复用的工程资产。' },
    how: { title: '工作方式', subtitle: '从 Team 定义到 OpenCode 运行，再到按复杂度选择执行方式。', steps: [{ step: '定义 Team', desc: '为不同任务 / 项目定义 Team、Leader、成员、规则、review 方式和完成标准。' }, { step: '投影到 OpenCode', desc: 'CrewBee 将 Team 定义投影为 OpenCode 中可选择、可运行、可委派的 Agent。' }, { step: '选择执行模式', desc: '简单任务走单 Agent，复杂任务启用多 Agent 协作、支援上下文和 review。' }, { step: '委派、回流、收口', desc: '支援 Agent 在独立上下文中完成专项任务，主 Agent 汇总高信号结论并最终收口。' }] },
    team: { badge: '模板体系', title: 'Team 是可复制、可修改、可贡献的工程资产。', paragraphs: ['CrewBee 把 Agent Team 组织成清晰的文件型资产。', '你可以使用内置 Coding Team，也可以复制模板，修改成员分工、共享规则、review 方式和完成标准，沉淀成自己的 Team。'], files: ['team.manifest.yaml      # Team 定位、Leader、成员和 workflow', 'team.policy.yaml        # 共享规则、安全边界和质量底线', 'coding-leader.agent.md  # 主 Agent / 上下文 owner / 最终收口者', 'codebase-explorer.agent.md', 'web-researcher.agent.md', 'reviewer.agent.md       # 独立 review 与完成标准', 'TEAM.md                 # 面向人的 Team 说明'] },
    codingTeam: { badge: 'Coding Team', title: '内置成熟 Coding Team。不只是一个 Coder。', subtitle: '面向代码开发、修复、调试、重构和验证，内置 Coding Team 提供清晰角色分工、review 方式与验收标准。', roles: [{ name: 'coding-leader', desc: '默认入口、主上下文 owner、最终收口者。' }, { name: 'coding-executor', desc: '执行明确实现、修复、调试与局部重构。' }, { name: 'codebase-explorer', desc: '定位代码入口、调用链、相似实现和历史线索。' }, { name: 'web-researcher', desc: '查官方资料、外部文档、开源实现和版本差异。' }, { name: 'reviewer', desc: '独立审查风险、遗漏、验证证据和完成标准。' }], gateTitle: 'Completion Gate', gates: ['目标问题已定位', '修改点有明确依据', '已完成必要实现或修复', '已运行可用的 diagnostics / build / tests', 'reviewer 未发现真实阻塞', '已说明未验证项和残余风险'] },
    projectContext: { badge: 'Next', title: '跨会话自动维护 Project Context。', subtitle: '让长期项目持续保有项目定位、框架设计、历史记录、当前状态与计划等摘要信息，减少重复解释和重复读代码。', cards: [{ title: '持续维护项目摘要', desc: '记录项目定位、框架设计、历史决策、当前状态、已知风险和下一步计划。' }, { title: '减少手动提示补充', desc: '新会话不再每次从零解释项目背景、历史决策和当前计划。' }, { title: '启发式阅读代码', desc: 'Agent 先根据 Project Context 定位相关模块，再进行针对性代码阅读，减少完整扫描工程代码带来的上下文消耗。' }], flow: ['Session Start：读取 Project Context，恢复项目定位和当前计划', 'During Work：根据摘要启发式阅读相关代码和资料', 'Session End：更新实现状态、决策、风险和下一步计划', 'Next Session：从最新项目上下文继续推进'] },
    builders: { title: '为构建者而生', subtitle: '面向那些已经手动维护智能体工作流的人。', cards: [{ role: 'OpenCode 重度用户', desc: '希望在 OpenCode 中使用更清晰的 Team、模式切换和委派协作，而不是维护一堆零散 agent 配置。' }, { role: 'Agent Workflow 构建者', desc: '希望把自己的工作方式沉淀成可运行、可复制、可贡献的 Agent Team。' }, { role: 'AI Coding 用户', desc: '希望简单代码任务保持轻量，复杂任务具备代码探索、review 和验收标准。' }, { role: '长期项目维护者', desc: '希望跨会话保留项目定位、框架设计、历史记录、当前状态和计划。' }] },
    opencode: { title: '当前已打通 OpenCode MVP 链路。', description: 'CrewBee 已经可以把 Team 定义投影为 OpenCode 中可选择、可运行、可委派的 Agent。', links: ['阅读安装指南', '查看 OpenCode 运行时文档'], proofs: ['Team / Agent 定义', 'Team Library 装配与校验', 'Runtime Projection', 'formal leader 默认入口选择', 'OpenCode agent 配置投影', 'session binding', 'delegation tooling', '用户级安装与 doctor 校验'] },
    faq: { badge: '常见问题', heading: ['清晰性', '来自', '结构。'], items: [{ q: 'CrewBee 是提示词包吗？', a: '不是。CrewBee 会使用 prompt，但核心不是 prompt 文本本身，而是 Team 定义、Agent Profile、Runtime Projection、session binding 和 delegation tooling。它把 Agent 工作方式整理成可维护、可运行的 Team 工程资产。' }, { q: 'CrewBee 会让所有任务都变成多 Agent 协作吗？', a: '不会。CrewBee 的目标是根据任务复杂度选择合适的执行方式。简单任务可以保持单 Agent 快速执行，复杂任务再启用支援 Agent、review、验证和完成闸门。' }, { q: '为什么需要主 Agent 持有最完整上下文？', a: '复杂任务中，不同支援 Agent 只会掌握部分信息。CrewBee 让主 Agent 汇总用户目标、项目约束、支援结论、review 意见和验证结果，保证关键决策依据更全面，最终收口更一致。' }, { q: '上下文隔离式委派是什么意思？', a: '支援 Agent 在独立上下文中完成代码探索、资料研究、review 或多模态解读，只把高信号结论回传给主 Agent。这样可以降低主 Agent 的上下文与注意力负担。' }, { q: 'CrewBee 当前支持哪些宿主？', a: '当前优先支持 OpenCode。CrewBee 的定义层尽量保持宿主无关，后续可以继续适配类似宿主。' }, { q: 'Project Context 现在已经完整实现了吗？', a: 'Project Context 是 CrewBee 下一阶段重点增强方向。目标是跨会话自动维护项目定位、框架设计、历史记录、当前状态与计划等摘要信息，减少重复解释和重复读代码。' }] },
    acknowledgements: { badge: '致谢', title: '受开源 Agent 生态启发。', paragraphs: ['CrewBee 受 OpenCode 以及 oh-my-openagent 等社区项目启发。这些项目让 Agent Team 工作流在真实开发环境中的价值变得更加清晰。', 'CrewBee 在这个方向上继续推进：把 Agent Team 进一步整理为可管理、可投影、可配置、可复用的工程资产。'] },
    footer: { docs: '文档', license: '许可证' }
  }
} as const;

export type Copy = typeof copy.en;
